name: Master CI/CD

on:
    push:
        branches:
            - master

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    release-and-deploy:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        concurrency:
            group: "production"
            cancel-in-progress: true

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 12

            - name: Setup Node.js
              uses: actions/setup-node@v7
              with:
                  node-version: 24
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Configure Git User
              run: |
                  git config --global user.name "MeloDev [Bot]"
                  git config --global user.email "melodiaz2111@gmail.com"

            - name: Validate Code
              run: |
                  pnpm lint
                  pnpm test

            - name: Automated Version Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
              run: |
                  pnpm release -- --ci --no-git.requireCleanWorkingDir --git.commitMessage="chore: release v\${version} [skip ci]"

            - name: Build Project
              run: pnpm build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v5
              with:
                  path: ./dist

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v5
